packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalog:
  '@eslint/js': ^9.36.0
  '@nestjs/cli': 11.0.10
  '@nestjs/common': 11.1.6
  '@nestjs/core': 11.1.6
  '@nestjs/platform-express': 11.1.6
  '@nestjs/swagger': ^11.2.0
  '@tailwindcss/vite': ^4.1.14
  '@types/express': ^5.0.3
  '@types/multer': ^2.0.0
  '@types/react': ^19.1.16
  '@types/react-dom': ^19.1.9
  '@typescript-eslint/eslint-plugin': ^8.46.0
  '@typescript-eslint/parser': ^8.46.0
  '@vitejs/plugin-react-swc': ^4.1.0
  antd: ^5.27.4
  concurrently: 9.2.1
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.22
  fast-glob: ^3.0.0
  globals: ^16.4.0
  live-server: ^1.2.2
  multer: ^2.0.2
  ofetch: ^1.4.1
  prettier: ^3.6.2
  react: ^19.1.1
  react-dom: ^19.1.1
  reflect-metadata: 0.2.2
  rxjs: 7.8.2
  tailwindcss: ^4.1.14
  typescript-eslint: ^8.45.0
  vitepress: 2.0.0-alpha.12
  wait-on: ^9.0.1

catalogs:
  cli:
    '@antfu/eslint-config': ^5.4.1
    '@antfu/ni': ^26.0.1
    bumpp: ^10.2.3
    eslint: ^9.36.0
    lint-staged: ^16.2.0
    simple-git-hooks: ^2.13.1
    tsdown: ^0.15.4
    tsx: ^4.20.6
    typescript: ~5.9.3
    vite: ^7.1.7
  inlined:
    '@antfu/utils': ^9.2.1
  testing:
    tinyexec: ^1.0.1
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/node': ^24.6.0
ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks

shellEmulator: true
