packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalog:
  '@nestjs/cli': ^11.0.0
  '@nestjs/common': ^11.0.0
  '@nestjs/core': ^11.0.0
  '@nestjs/platform-express': ^11.0.0
  '@nestjs/swagger': ^11.2.0
  '@types/express': ^5.0.3
  '@types/multer': ^2.0.0
  concurrently: ^9.0.0
  fast-glob: ^3.0.0
  live-server: ^1.2.2
  multer: ^2.0.2
  prettier: ^3.6.2
  reflect-metadata: ^0.2.0
  rxjs: ^7.0.0

catalogs:
  cli:
    '@antfu/eslint-config': ^5.4.1
    '@antfu/ni': ^26.0.1
    bumpp: ^10.2.3
    eslint: ^9.36.0
    lint-staged: ^16.2.0
    simple-git-hooks: ^2.13.1
    tsdown: ^0.15.4
    tsx: ^4.20.5
    typescript: ^5.9.2
    vite: ^7.1.7
  inlined:
    '@antfu/utils': ^9.2.1
  testing:
    tinyexec: ^1.0.1
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/node': 24.5.2

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks

shellEmulator: true
